apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookstore-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - bookstore.example.com
      secretName: bookstore-tls
  rules:
    - host: bookstore.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bookstore-app-service
                port:
                  number: 80
